from database import Base, db

from models.raw_consulta_estoque_bot import ConsultaEstoqueBOT
from models.raw_consulta_estoque_eud import ConsultaEstoqueEUD
from models.raw_consulta_estoque_qdb import ConsultaEstoqueQDB
from models.raw_pedido_semanal_especial import PedidoSemanalEspecial
from models.raw_ruptura_total_bot import RupturaTotalBot
from models.usuarios import Usuario
from models.raw_relatorio_abc_vendas import RelatorioAbcVendas

Base.metadata.create_all(bind=db)